x-airflow-common: &airflow-common
  image: apache/airflow:3.1.0
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
    AIRFLOW__API_AUTH__JWT_SECRET: "szakdolgozat-airflow-jwt-secret-change-me"
    AIRFLOW__API__SECRET_KEY: "szakdolgozat-airflow-api-secret-change-me"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-webserver:8080/execution/
    AIRFLOW__CORE__FERNET_KEY: "MnOpicIrcwYhwJ6h1mUwXpU3oQvmsji1KMpQLTDd4kM="
    PYTHONPATH: /opt/airflow
    _PIP_ADDITIONAL_REQUIREMENTS: "dbt-postgres"
    DBT_PROFILES_DIR: /opt/airflow/dbt
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./Source_Generator/data:/opt/airflow/data
    - ./airflow/src:/opt/airflow/src
    - ./dbt:/opt/airflow/dbt
    

services:
  postgres:
    image: postgres:16
    container_name: szakdolgozat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retail_dwh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow-init:
    <<: *airflow-common
    container_name: szakdolgozat-airflow-init
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow connections delete retail_dwh || true
        airflow connections add 'retail_dwh' --conn-uri 'postgres://postgres:postgres@postgres:5432/retail_dwh'

  airflow-webserver:
    <<: *airflow-common
    container_name: szakdolgozat-airflow-webserver
    restart: unless-stopped
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    command: api-server

  airflow-scheduler:
    <<: *airflow-common
    container_name: szakdolgozat-airflow-scheduler
    restart: unless-stopped
    depends_on:
      - postgres
      - airflow-init
    command: scheduler
    
  airflow-dag-processor:
    <<: *airflow-common
    container_name: szakdolgozat-airflow-dag-processor
    restart: unless-stopped
    depends_on:
      - postgres
      - airflow-init
    command: dag-processor
  
  
  dbt:
    build:
      context: ./dbt
    container_name: szakdolgozat-dbt
    working_dir: /usr/app
    volumes:
      - ./dbt:/usr/app
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml:ro
    profiles:
      - dbt
volumes:
  postgres_data: